FROM node:14
COPY start.sh /
WORKDIR /usr/src/app
COPY . .
WORKDIR /usr/src/app/frontend
RUN npm ci
RUN npm install --no-save webpack-cli@4.10.0
RUN ./node_modules/.bin/webpack --mode production
WORKDIR /usr/src/app/backend
RUN npm ci
RUN npm install --no-save typescript@4.1.3
RUN ./node_modules/.bin/tsc
ENTRYPOINT ["sh", "/start.sh"]
