#!/usr/bin/env python3
"""
Bounded WannaCry-style worm simulator for SEED Emulator labs.

This is not an SMB exploit and it does not scan the public Internet. It reads a
fixed target list generated by the emulator and sends a lab infection message to
the vulnerable service installed on those hosts.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import random
import socket
import time


LOG_FILE = "/tmp/wannacry_lab_worm.log"
START_MARKER = "/tmp/wannacry_lab_worm_started"
KILL_SWITCH_DOMAIN = "www.example.net"
KILL_SWITCH_PAUSE = "1.1.1.10"
KILL_SWITCH_CONTINUE = "1.1.1.20"
KILL_SWITCH_EXIT = "1.1.1.30"
KILL_SWITCH_RESERVED = "1.1.1.40"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a bounded WannaCry-style worm simulator.")
    parser.add_argument("--targets-file", default="/opt/wannacry-lab/targets.txt")
    parser.add_argument("--port", type=int, default=445)
    parser.add_argument("--token", default="seedemu-wannacry-lab")
    parser.add_argument("--connect-timeout", type=float, default=1.0)
    parser.add_argument("--delay", type=float, default=0.05, help="delay between target attempts")
    parser.add_argument("--jitter", type=float, default=0.05, help="extra random delay")
    parser.add_argument("--allow-prefix", action="append", default=["10."], help="allowed target IP prefix")
    parser.add_argument("--kill-switch-domain", default=KILL_SWITCH_DOMAIN)
    parser.add_argument("--kill-switch-poll", type=float, default=2.0)
    parser.add_argument("--once", action="store_true", help="exit immediately if this host already launched the worm")
    return parser.parse_args()


def log(message: str) -> None:
    path = Path(LOG_FILE)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"{time.time():.3f} {message}\n")


def load_targets(path: str, allowed_prefixes: list[str]) -> list[str]:
    targets = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if not any(line.startswith(prefix) for prefix in allowed_prefixes):
            log(f"skip target outside allowed prefixes target={line}")
            continue
        targets.append(line)
    random.shuffle(targets)
    return targets


def attempt_infection(target: str, port: int, token: str, timeout: float) -> bool:
    request = f"INFECT {token}".encode()
    try:
        with socket.create_connection((target, port), timeout=timeout) as sock:
            sock.sendall(request)
            sock.settimeout(timeout)
            response = sock.recv(512).decode(errors="ignore").strip()
            log(f"target={target} response={response!r}")
            return response.startswith("OK") or response.startswith("ALREADY")
    except OSError as exc:
        log(f"target={target} error={exc}")
        return False


def resolve_kill_switch(domain: str) -> str:
    try:
        return socket.gethostbyname(domain)
    except OSError as exc:
        log(f"kill_switch domain={domain} error={exc}")
        return ""


def wait_for_continue(args: argparse.Namespace) -> bool:
    """Return True when spreading may continue, False when the worm should exit."""
    while True:
        state = resolve_kill_switch(args.kill_switch_domain)
        if state == KILL_SWITCH_EXIT:
            log(f"kill_switch state={state} action=exit")
            return False
        if state == KILL_SWITCH_PAUSE:
            log(f"kill_switch state={state} action=pause")
            time.sleep(args.kill_switch_poll)
            continue
        if state == KILL_SWITCH_RESERVED:
            log(f"kill_switch state={state} action=reserved")
            return True
        if state and state != KILL_SWITCH_CONTINUE:
            log(f"kill_switch state={state} action=unknown-continue")
        else:
            log(f"kill_switch state={state or '<unresolved>'} action=continue")
        return True


def main() -> int:
    args = parse_args()
    marker = Path(START_MARKER)
    if args.once and marker.exists():
        log("worm already launched on this host; exiting")
        return 0
    marker.write_text(str(time.time()) + "\n", encoding="utf-8")

    targets = load_targets(args.targets_file, args.allow_prefix)
    log(f"starting bounded worm targets={len(targets)} port={args.port}")

    successes = 0
    for target in targets:
        if not wait_for_continue(args):
            print(f"attempts={len(targets)} successes={successes} stopped_by_kill_switch=true")
            return 0
        if attempt_infection(target, args.port, args.token, args.connect_timeout):
            successes += 1
        time.sleep(args.delay + random.random() * args.jitter)

    log(f"finished bounded worm successes={successes} attempts={len(targets)}")
    print(f"attempts={len(targets)} successes={successes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
