
from __future__ import annotations
from seedemu.core import AddressFamily, Node, Service, Server, normalizeAddressFamily
from seedemu.core.Emulator import Emulator
from seedemu.services.EthereumService import *
from .FaucetUtil import *
from typing import Union

# This service is a base code of a service utilizing faucetServer.


class FaucetUserServer(Server):
    """!
    @brief The FaucetServer class.
    """
    DIR_PREFIX = "faucet_user"

    __faucet_util:FaucetUtil
    __faucet_port: int
    __faucet_vnode_name:set
  
    def __init__(self, endpointAddressFamily: Union[AddressFamily, str, int] = AddressFamily.IPv4):
        """!
        @brief FaucetServer constructor.
        """
        super().__init__()
        self.__faucet_util = FaucetUtil(endpointAddressFamily=endpointAddressFamily)

    def setEndpointAddressFamily(self, family: Union[AddressFamily, str, int]) -> FaucetUserServer:
        """!
        @brief Set address family for faucet URLs generated for this user.

        @param family address family.

        @returns self, for chaining API calls.
        """
        self.__faucet_util.setEndpointAddressFamily(family)
        return self

    def setFaucetServerInfo(self, vnode: str, port = 80):
        """
        @brief set account from key string.
        
        @param keyString key string.

        @param isEncrypted indicates if the keyString is encrypted or not.

        @param password password of the key.

        @returns self, for chaining API calls.
        """
        
        self.__faucet_vnode_name = vnode
        self.__faucet_port = port
        
    def configure(self, emulator:Emulator):
        self.__faucet_util.setFaucetServerInfo(vnode=self.__faucet_vnode_name, 
                                               port=self.__faucet_port)
        self.__faucet_util.configure(emulator)

    def install(self, node: Node):
        """!
        @brief Install the service.
        """
        node.appendClassName("FaucetUserService")
        node.addSoftware('python3 python3-pip')
        node.addBuildCommand('pip3 install eth_account==0.5.9 requests')
        node.setFile(self.DIR_PREFIX + '/fundme.py', 
                     FaucetServerFileTemplates['fundme'].format(
                           faucet_url=self.__faucet_util.getFacuetUrl(),
                           faucet_fund_url=self.__faucet_util.getFaucetFundUrl()))
        node.appendStartCommand('chmod +x {}/fundme.py'.format(self.DIR_PREFIX))
        node.appendStartCommand(self.DIR_PREFIX + '/fundme.py')

    def print(self, indent: int) -> str:
        out = ' ' * indent
        out += 'Faucet user server object.\n'

        return out

class FaucetUserService(Service):
    """!
    @brief The FaucetUserService class.
    """
    __faucet_port: int
    __faucet_vnode_name:set
    __endpoint_address_family: AddressFamily
    
    def __init__(self, endpointAddressFamily: Union[AddressFamily, str, int] = AddressFamily.IPv4):
        """!
        @brief FaucetUserService constructor.
        """
        super().__init__()
        self.addDependency('Base', False, False)
        self.__endpoint_address_family = normalizeAddressFamily(endpointAddressFamily)

    def setEndpointAddressFamily(self, family: Union[AddressFamily, str, int]) -> FaucetUserService:
        """!
        @brief Set address family for faucet URLs generated by user servers.

        @param family address family.

        @returns self, for chaining API calls.
        """
        self.__endpoint_address_family = normalizeAddressFamily(family)
        for server in self._pending_targets.values():
            server.setEndpointAddressFamily(self.__endpoint_address_family)
        return self

    def setFaucetServerInfo(self, vnode: str, port = 80):
        """
        @brief set account from key string.
        
        @param keyString key string.

        @param isEncrypted indicates if the keyString is encrypted or not.

        @param password password of the key.

        @returns self, for chaining API calls.
        """
        
        self.__faucet_vnode_name = vnode
        self.__faucet_port = port

    def _createServer(self) -> Server:
        return FaucetUserServer(self.__endpoint_address_family)
    
    def configure(self, emulator: Emulator):
        super().configure(emulator)

        for (server, node) in self.getTargets():
            server.setFaucetServerInfo(self.__faucet_vnode_name, self.__faucet_port)
            server.configure(emulator)
        return 
    
    
    def getName(self) -> str:
        return 'FaucetUserService'

    def print(self, indent: int) -> str:
        out = ' ' * indent
        out += 'FaucetUserServiceLayer\n'

        return out
    
